### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by rubenheymans** [nineinchnick/yii2-nfy#6]
Copy migrations to your migrations folder and adjust dates in file and class names. Then apply migrations.

yii migrate/up --migrationPath=@nineinchnick/nfy/migrations

**Comment by nineinchnick** [comment]
The sentence you pasted from the README clearly says to copy the migrations, not run them from the module directly.

**Comment by rubenheymans** [comment]
I'm just saying, using yii migrate with the migrationPath param is faster  
why should I copy them to my migrations folder?

**Comment by nineinchnick** [comment]
I don't know if it's still the case in Yii2, but in Yii1 if you ran migrations with older dates than those in the project you can't revert them. That's why I advise to copy the migrations and adjust the dates to keep the order.
