### ISSUE TITLE
install

### ISSUE THREAD

**Issue by egozo** [nineinchnick/yii2-nfy#9]
Can anybody help with install this module?

**Comment by nineinchnick** [comment]
Please describe what steps have you already taken. Installation should be described in the readme file, it may however be unclear.

**Comment by egozo** [comment]
hello

1)  Installed package via  composer
2)  Updated config file ( main and console configs)
3)   Check out the Module (app -> common)
4) A pplied migrations.
5) copied controllers, modules, view, widgets from distr to frontend
6) tried to make new menu (views/layout/main)   'url' => ['/queue/index'],  with action, but have 404




>Вторник, 21 июля 2015, 1:20 -07:00 от Jan Waś <notifications@github.com>:
>
>Please describe what steps have you already taken. Installation should be described in the readme file, it may however be unclear.
>—
>Reply to this email directly or view it on GitHub .


С уважением,
Тимофей П.
tp@inbox.ru

**Comment by nineinchnick** [comment]
I don't know why are you copying files in step 5 and what are you trying to do in step 6.
